name: Deploy to GitHub Pages
'on':
  - workflow_dispatch
jobs:
  deploy:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16.x
          cache: yarn
      - name: Build
        run: |
          yarn install
          yarn clean
          yarn build
          cd public
          echo "blog.redish101.tk" >> CNAME
          cd ..
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          publish_branch: gh-pages
